buildscript {
    ext {
        kotlin_version = "1.8.0"
        nav_version = "2.5.3"
        room_version = "2.5.0"
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath 'com.android.tools.build:gradle:8.0.0'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}